version: "3"

services:
  acer:
    image: nginx:alpine
    ports:
      - "16001:80"
    volumes:
      - ./html:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  php:
    build: .
    volumes:
      - ./html:/var/www/html
  db:
    image: mysql:5.7
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./persist:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "battles"
      MYSQL_ROOT_PASSWORD: "root"
