sgc_nginx:
    image: nginx:latest
    ports:
        - "14601:80"
    volumes:
        - ./public:/public
        - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
        - sgc_php
sgc_php:
    image: php:7-fpm
    volumes:
        - ./public:/public

